name: Build and publish UI

on:
  push:
    branches:
      - master
    paths:
      - 'services/ui/**'
      - 'services/backend/src/apiTypes'
      - '!services/ui/dev/**'
      - '!services/ui/discord-movie-list/README.md'
  pull_request:
    branches:
      - master
    paths:
      - 'services/ui/**'
      - 'services/backend/src/apiTypes'
      - '!services/ui/dev/**'
      - '!services/ui/discord-movie-list/README.md'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        if: ${{ contains(fromJson('["push"]'), github.event_name) }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mardotio/discord-movie-list-ui
          tags: |
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: services/ui/Dockerfile
          push: ${{ contains(fromJson('["push"]'), github.event_name) }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
