name: Test and Lint UI

on:
  push:
    branches:
      - master
    paths:
      - 'services/ui/discord-movie-list/**'
      - '!services/ui/discord-movie-list/README.md'
  pull_request:
    branches:
      - master
    paths:
      - 'services/ui/discord-movie-list/**'
      - '!services/ui/discord-movie-list/README.md'

jobs:
  test-and-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Lint UI
        run: npm run lint
